import { Poppins } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { SessionsProvider } from '@/components/core/SessionProvider';
import { SidebarProvider } from '@/components/ui/sidebar';

const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: 'Sistem Pengaduan Masyarakat',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.variable}antialiased`}
      >
        <SidebarProvider>
          <SessionsProvider>
            <main className='min-h-screen w-full'>
              {children}
              <Toaster richColors />
            </main>
          </SessionsProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
